services:
  app:
    container_name: timers_app
    image: docker.io/node:24.5.0-alpine
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: sh -c 'cd /app && npm start'
    networks:
      podman_network:
        aliases:
          - timers-app
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    deploy:
      resources:
        limits:
          cpus: ${TIMERS_APP_CPUS}
          memory: ${TIMERS_APP_MEMORY}
    # depends_on:
    #   - db
  db:
    container_name: timers_db
    image: docker.io/mongo:7.0.16
    networks:
      podman_network:
        aliases:
          - timers-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${TIMERS_DB_CPUS}
          memory: ${TIMERS_DB_MEMORY}
networks:
  podman_network:
    external: true
    # driver: bridge
