services:
  app:
    container_name: app
    image: docker.io/node:24.5.0-alpine
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: sh -c 'cd /app && npm start'
    networks:
      timers_network:
        aliases:
          - app
    restart: unless-stopped
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: ${APP_CPUS}
          memory: ${APP_MEMORY}
  db:
    container_name: db
    image: docker.io/mongo:7.0.16
    networks:
      timers_network:
        aliases:
          - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${DB_CPUS}
          memory: ${DB_MEMORY}
networks:
  timers_network:
    driver: bridge
