services:
  app:
    container_name: timers_app
    image: docker.io/node:20.18.1-bookworm
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: sh -c 'cd /app && npm start'
    networks:
      podman_network:
        aliases:
          - timers-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${TIMERS_APP_CPUS}
          memory: ${TIMERS_APP_MEMORY}
  depends_on:
    - db
  db:
    container_name: timers_db
    image: docker.io/mongo:7.0.16
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TIMERS_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TIMERS_DB_PASSWORD}
    networks:
      podman_network:
        aliases:
          - timers-db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${TIMERS_DB_CPUS}
          memory: ${TIMERS_DB_MEMORY}
networks:
  podman_network:
    external: true
